### ISSUE TITLE
[PLAN] Release 0.4.0

### ISSUE THREAD

**Issue by dshafik** [akamai/AkamaiOPEN-edgegrid-php-client#7]
This ticket outlines the plan for release 0.4.0
- [x] Move away from using `\Exception` to more appropriate, and package specific exceptions (See #13)
- [x] Add support for PSR-7 requests (e.g. `->send()` and `->sendAsync()`)
- [x] Add CLI interface to PHAR release file (See #8)
- [x] Use a custom User-Agent (See #10) 
## Other Changes
- Fix issue with string query args (See #12)
- Show request body when using the verbose handler (See #11)
